### ISSUE TITLE
Command block structure generates in world near spawn

### ISSUE THREAD

**Issue by Herobattler** [jtorleonstudios/HUB-Awesome-Dungeon#13]
Command block structure generates in world near spawn

**Comment by jtorleonstudios** [comment]
We do not use command blocks for our structures. Do you have a picture?

**Comment by Herobattler** [comment]
No picture but its basically a few chain command blocks and restone observers. The command blocks hold commands for structures and entities. 

Forge: 1.19.2/43.1.52
and
Awesome dungeon 3.1.0 - Forge 1.19.2

**Comment by jtorleonstudios** [comment]
We do not use command_block, chain_command_block or observer to generate our structure. Our structures are generated using JAVA programming and Datapacks. 

These must come from another mods/datapack you have. 

Please take a picture to clarify the situation because I can't find any block in my tests.
